name: draft release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:
  draft-release:
    runs-on: ubuntu-latest

    steps:
      - uses: release-drafter/release-drafter@09c613e259eb8d4e7c81c2cb00618eb5fc4575a7 # v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
